### ISSUE TITLE
How can I download this?

### ISSUE THREAD

**Issue by cambrownie5777** [johnathon-walnut/skinchangerStandalone#4]
Greetings fellow humans, I would like to know how I can go about downloading this project to my computer! I can not seem to find any release to download the binary in order to inject it.

**Comment by SDarkra1** [comment]
Check actions tab

**Comment by johnathon-walnut** [comment]
You can either download it from the actions page (https://github.com/johnathon-walnut/skinchangerStandalone/actions), or just compile it yourself
